### ISSUE TITLE
Request to have option of triggering LongPress event as soon as the long press time has passed

### ISSUE THREAD

**Issue by vyagi** [mathertel/OneButton#100]
Currently, to achieve the long press you need to press the button and hold it pressed for sufficient time. The long press event is triggered after you release the button. Hence, you don't know if the time for recognizing the long press has passed or not. It would be nice if it was configurable to set it up for triggering the long press event as soon as the long press time passed has been detected.

**Comment by mathertel** [comment]
The longPressStart event does exactly this.
