### ISSUE TITLE
ESP32 and FreeRTOS

### ISSUE THREAD

**Issue by mitchsf** [mathertel/OneButton#103]
Has anyone else tried this? When tick() is run in a task, the function crashes with errors that I'm not clear on. Lines 56 and 199 of OneButton.cpp indicate it has something to do with pinMode or digitalRead, according to the Exception Decoder.

It works perfectly if tick() is in loop(), but with FreeRTOS, it's not the best idea to have anything running there.

**Comment by mitchsf** [comment]
I tried using a semaphore to block anything else from running, to no effect.

`void RunFunctions( void * parameter) {
  for (;;) {
    xSemaphoreTake(buttonMutex, portMAX_DELAY);
    button.tick();
    xSemaphoreGive(buttonMutex);
    vTaskDelay(10);
  }
}`

**Comment by mathertel** [comment]
I am not aware of such a problem.
Can you please investigate more and share your findings ?

**Comment by mitchsf** [comment]
Sorry, I don't know enough about FreeRTOS to figure this one out. I just left tick() in loop().
