### ISSUE TITLE
ESP32: Pull-down support

### ISSUE THREAD

**Issue by ModischFabrications** [mathertel/OneButton#106]
OneButton(pin, true, true) supports only pull-ups, but some chips (notably the ESP32) offer pull-down as well. Is there any other method I couldn't find or are users limited to only pull-ups?

**Comment by mathertel** [comment]
Have a look at the example `SpecialInput.ino`.
Here the pinMode is set outside of the library and you can set it for ESP32 with a INPUT_PULLDOWN.
