### ISSUE TITLE
Add library to Platformio

### ISSUE THREAD

**Issue by dontsovcmc** [mathertel/OneButton#11]
Platformio is command line tool to fast development.

information about library description file:
http://docs.platformio.org/en/stable/librarymanager/creating.html

here example: https://github.com/PaulStoffregen/Time/blob/master/library.json
finish type: platformio lib register https://github.com/mathertel/OneButton/blob/master/library.json

**Comment by lovegandhi** [comment]
It shows up for me on PlatformIO

**Comment by mathertel** [comment]
Good to hear that. Thanks

Am 28.06.2017 4:49 vorm. schrieb Taulant Dhami <notifications@github.com>:

It shows up for me on PlatformIO
