### ISSUE TITLE
ESP32CAM only pin 4 working

### ISSUE THREAD

**Issue by borki74** [mathertel/OneButton#115]
Hi, 
I'm trying to use the library with an ESP32Cam module, but i can only get it to work with pin 4. All other pins do not respond.

Please help,
Matt

**Comment by mathertel** [comment]
Have a look at recommendations: 
<https://lastminuteengineers.com/esp32-cam-pinout-reference/#which-esp32cam-gpios-are-safe-to-use>
This board has only a few options for using GPIO pins.
