### ISSUE TITLE
type mismatch for setPressTicks

### ISSUE THREAD

**Issue by JM-FRANCE** [mathertel/OneButton#117]
in the function [setPressTicks](https://github.com/mathertel/OneButton/blob/f5448ef67f0d05726a6eefd09b0c726f732a4660/src/OneButton.cpp#L76-L80) you pass an int and you store the result in an unsigned int

it would make sense to have the same type for everything and since it's a duration in ms unsigned makes sense. Given the variability of platforms for unsigned int, I would recommend to fix this to either uint16_t or uint32_t (the former could make sense to limit RAM usage since you would not expect a long press delay of more than 32.768 seconds to be used)

**Comment by mathertel** [comment]
This was fixed before version 2.5.0.

Thanks for pointing out.
