### ISSUE TITLE
Using internal pullup resistor

### ISSUE THREAD

**Issue by emrekilic** [mathertel/OneButton#14]
I am using this library with nodemcu module. When i use TwoButtons example without using any resistor and connect button to pin and gnd, long press event never stops. I thought it was floating issue because i didn't set INPUT_PULLUP in anywhere. After that in setup() i set this pins to INPUT_PULLUP and worked flawlessly. What is your suggestions to use internal pullups? Changing library or setting it manually in setup()?

**Comment by mathertel** [comment]
Was fixed in march 2017.
