### ISSUE TITLE
Does one button support i2c IO expander such as TCA9548A?

### ISSUE THREAD

**Issue by xnaron** [mathertel/OneButton#146]
I'm out of digital input pins on an esp8266 project and am looking to get an I2C based IO expander that uses a TCA9548A chip.    Similar to this one https://learn.adafruit.com/adafruit-tca9548a-1-to-8-i2c-multiplexer-breakout/arduino-wiring-and-test .

Will the OneButton library work with this?

**Comment by mathertel** [comment]
It is not intended to support this.

**Comment by mathertel** [comment]
There is the SpecialInput example that might help you:
read the level of the button using the specific functionality and then pass he current HIGH/LOW value to the tick(...) function.
