### ISSUE TITLE
ERRROR compiling example SimpleOnButton

### ISSUE THREAD

**Issue by maxelle** [mathertel/OneButton#147]
Compiling your simple example I receive this error

c:\Arduino2\libraries\OneButton\src\OneButton.cpp: In constructor 'OneButton::OneButton(int, bool, bool)':
c:\Arduino2\libraries\OneButton\src\OneButton.cpp:33:7: error: too many arguments to function 'void init()'
   33 |   init(pin, pullupActive ? INPUT_PULLUP : INPUT, activeLow);
      |   ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from c:\Arduino2\libraries\OneButton\src\OneButton.h:28,
                 from c:\Arduino2\libraries\OneButton\src\OneButton.cpp:19:

**Comment by dsagdfgsFD** [comment]
Had the same issue. @thebentern solution fixed it for me!
Thanks!
