### ISSUE TITLE
You actually fixed this issue while I was reporting it - thank you!

### ISSUE THREAD

**Issue by EvanBarnesCL** [mathertel/OneButton#149]
There was a compiler problem with version 2.6.0 of the library, but literally as I was writing this up, you uploaded 2.6.1, which fixed it! Thank you! I love this library, I use it in so many projects. Also you released 2.6 yesterday, which added a new feature that solved a problem I was having just today! I really appreciate the constant improvements.

**Comment by mathertel** [comment]
Thanks for reporting anyway. Thinks happen .... Sorry.
