### ISSUE TITLE
using more than one button

### ISSUE THREAD

**Issue by zjjxxsh** [mathertel/OneButton#150]
Can I use OneButton for more than one button? I use more than one button but it returns some wrong data. For example, when I press button2, button1 press event is activated.

**Comment by mathertel** [comment]
The TwoButtons Example demonstrates that multiple buttons can be used at the same time.

**Comment by X-Filess** [comment]
possible make dynamic count buttons ? for example, i in web want configure - pin is button or not.
I don't want add in sketch 53 buttons class for it..
