### ISSUE TITLE
Feature request; analog read buttons

### ISSUE THREAD

**Issue by cranefist** [mathertel/OneButton#152]
I like your library, its simple and cleans up my code so i use it often. 

I was thinking if it would be possible to add buttons based on analog values.

This way it would be possible to use a single wire for multiple buttons, using voltage dividers.

So that i could set an analog read value for a given button and a pin. And then set multiple buttons for this same pin with different values. It would require also some sort of setting for buffer, like if i set a analog value of 1000 as one button. It would register values from 950 - 1050 for this button. As there will always be noise and ADC:s are not that accurate on these MCUs.

**Comment by mathertel** [comment]
By default the OneButton library uses the digitalRead function for input. However, the SpecialInput.ino example 
demonstrates to implement your own function that returns High or LOW but can use any source.

> This is a sample sketch to show how to use the OneClick library on other input sources than standard digital pins.

Hope that gives you directions.
