### ISSUE TITLE
Single Click with Interrupt possible?

### ISSUE THREAD

**Issue by VolkerBo** [mathertel/OneButton#28]
I tried to realize a solution with interrupt and **single click.**
But I can not get it to work.

My function works **every second single click** or **every double click**, but not on **single clicks**.

I want to realize a state machine that switches to the next state with every **single click**.

[TasterTest3.txt](https://github.com/mathertel/OneButton/files/1699355/TasterTest3.txt)

// Taster
#include "OneButton.h" 
// The actions I ca do... 
typedef enum { 
ACTION_NONE, 		// Wertauswahl reset
ACTION_VORGABE, // Wertauswahl
ACTION_WAHL, 		// Wertübernahme
ACTION_A, 			// test
ACTION_B, 			// test
ACTION_C 				// test
} 
MyActions; 

// Setup a new OneButton on pin A1. 
OneButton button(A1, true); 

MyActions nextAction = ACTION_NONE; // no action when starting 

//Setup-----------------------------------------------------------------------------------------
void setup() {
  Serial.begin(9600);
	
	// link the myClickFunction function to be called on a click event. 
	button.attachClick(myClickFunction); 

	// link the doubleclick function to be called on a doubleclick event. 
	//button.attachDoubleClick(myDoubleClickFunction); 

  // You may have to modify the next 2 lines if using another pin than A1
  PCICR |= (1 << PCIE1);    // This enables Pin Change Interrupt 1 that covers the Analog input pins or Port C.
  PCMSK1 |= (1 << PCINT9);  // This enables the interrupt for pin 1 of Port C: This is A1.
	
// set # millisec after safe click is assumed.
	button.setDebounceTicks(50);

// set # millisec after single click is assumed.
	button.setClickTicks(500);

// set # millisec after press is assumed.
//button.setPressTicks(1000); //z.Z. nicht genutzt

}

// Main------------------------------------------------------------------------------------------
void loop() {

	Serial.print("Nextaction: ");
	Serial.println(nextAction);
	delay(900);
	
} // Ende Loop

// Taster
// this function will be called when the button was pressed 1 time and them some time has passed. 
void myClickFunction() { 
if (nextAction == ACTION_NONE) { 
nextAction = ACTION_VORGABE;
Serial.println("VORGABE");
}	else if (nextAction == ACTION_VORGABE) {
nextAction = ACTION_WAHL; 
Serial.println("WAHL");
}	else if (nextAction == ACTION_WAHL) {
nextAction = ACTION_A; 
Serial.println("A");
}	else if (nextAction == ACTION_A) {
nextAction = ACTION_B; 
Serial.println("B");
}	else if (nextAction == ACTION_B) {
nextAction = ACTION_C;
Serial.println("C");
}	else if (nextAction == ACTION_C) {
nextAction = ACTION_NONE;    
}  
}	// myClickFunction 
/*
// this function will be called when the button was pressed 2 times in a short timeframe. 
void myDoubleClickFunction() { 
if (nextAction == ACTION_VORGABE) { 
			//l = zykvar[k-1];
nextAction = ACTION_WAHL; 

} else if (nextAction == ACTION_A) { 
//nextAction = ACTION_NONE; 
//Do nothing
}
} // myDoubleClickFunction 
*/

// The Interrupt Service Routine for Pin Change Interrupt 1
// This routine will only be called on any signal change on A1: exactly where we need to check.
ISR(PCINT1_vect) {
  // keep watching the push button:
  button.tick(); // just call tick() to check the state.
}

Could anyone help?

Regards 
Volker

**Comment by VolkerBo** [comment]
So I found out for myself.

![click](https://user-images.githubusercontent.com/36196646/35907919-8ff19dba-0bef-11e8-8695-756d5989f013.PNG)

One needs an edge to the transition to 1.
You need a second edge to transition to 2.
And finally you need a third flank to transition to click ().

Therefore you can not use "click ()" with interrupt.

Tell me if I am wrong.

Regards
Volker

**Comment by gitmeister** [comment]
I'm having exactly the same behavior. I'm using the library PinChangeInterrupt (https://github.com/NicoHood/PinChangeInterrupt) and all works Ok except the click() is only called on the second button press. I don't see a reason other than tick() is only being called on transitions and the debounce code may want to see tick() with a consistent button state. I'll post if I get a solution.

**Comment by gitmeister** [comment]
Here's a fix that i've tested works. Insert at Line 133 of OneButton.cpp:

```
  } else if (_state == 1) { // waiting for menu pin being released.

    if ((buttonLevel == _buttonReleased) && ((unsigned long)(now - _startTime) < _debounceTicks)) {
      // button was released to quickly so I assume some debouncing.
	    // go back to state 0 without calling a function.
      _state = 0;
// INSERT THIS >>>>     
    } else if ((buttonLevel == _buttonReleased) && (unsigned long)(now - _startTime) > _clickTicks) {
      // this was only a single short click
      if (_clickFunc) _clickFunc();
      _state = 0; // restart.  
// <<<< INSERT THIS
    } else if (buttonLevel == _buttonReleased) {
      _state = 2; // step to state 2
      _stopTime = now; // remember stopping time
```

**Comment by foxsam21** [comment]
> Here's a fix that i've tested works. Insert at Line 133 of OneButton.cpp:
In the current code it would be line 206:
```
    if ((!activeLevel) &&
        ((unsigned long)(now - _startTime) < _debounceTicks)) {
      // button was released to quickly so I assume some debouncing.
      // go back to state 0 without calling a function.
      _state = 0;

  // INSERT THIS >>>> based on: https://github.com/mathertel/OneButton/issues/28#issuecomment-377613782   
    } else if ((!activeLevel) &&
        ((unsigned long)(now - _startTime) < _clickTicks)) {
      // this was only a single short click
      if (_clickFunc) _clickFunc();
      _state = 0; // restart.  
  // <<<< END INSERT THIS

    } else if (!activeLevel) {
      _state = 2; // step to state 2
      _stopTime = now; // remember stopping time
```




> PS: This is a quick hack since if you try to do a double click it won't work as expected as it'll give 2xclicks.

Is there anything anyone has done to get this working properly?

**Comment by antno1000** [comment]
> 
> 
> > Here's a fix that i've tested works. Insert at Line 133 of OneButton.cpp:
> 
> In the current code it would be line 206:
> 
> ```
>     if ((!activeLevel) &&
>         ((unsigned long)(now - _startTime) < _debounceTicks)) {
>       // button was released to quickly so I assume some debouncing.
>       // go back to state 0 without calling a function.
>       _state = 0;
> 
>   // INSERT THIS >>>> based on: https://github.com/mathertel/OneButton/issues/28#issuecomment-377613782   
>     } else if ((!activeLevel) &&
>         ((unsigned long)(now - _startTime) < _clickTicks)) {
>       // this was only a single short click
>       if (_clickFunc) _clickFunc();
>       _state = 0; // restart.  
>   // <<<< END INSERT THIS
> 
>     } else if (!activeLevel) {
>       _state = 2; // step to state 2
>       _stopTime = now; // remember stopping time
> ```
> 
> > PS: This is a quick hack since if you try to do a double click it won't work as expected as it'll give 2xclicks.
> 
> Is there anything anyone has done to get this working properly?
> 
> Edit:
> It seems to be working fine for me without this edit... maybe it was fixed? (if so this should be closed...)

This code enables click but disables doublclick feature, can't use doubleclick now

**Comment by mathertel** [comment]
Please check for version 2.0.0 and be sure to call tick() in the main loop() function, not only in interrupt routines.
