### ISSUE TITLE
debounce

### ISSUE THREAD

**Issue by gregorshaus** [mathertel/OneButton#3]
Hi, I had some problems with the library. If the Input is dedected with _buttonPressed for one time a click is detected without debounce. I implemented a debounce-time (step 7):

void OneButton::tick(void)
{
  // Detect the input information 
  int buttonLevel = digitalRead(_pin); // current button signal.
  unsigned long now = millis(); // current (relative) time in msecs.

  // Implementation of the state machine
  if (_state == 0) { // waiting for menu pin being pressed.
    if (buttonLevel == _buttonPressed) {
      _state = 7; // step to state 1
      _startTime = now; // remember starting time
    } // if

  } else if (_state == 7) { // debounce check if the button is really pressed
    if ((buttonLevel == _buttonPressed) && (now > _startTime + _debounce)) {
      _state = 1; // OK button pressed for debounce- time. step to state 1
    } // if
	if (buttonLevel == _buttonReleased) {
	   _state = 0; // STOP step to state 0
	}

  } else if (_state == 1) { // waiting for menu pin being released.
    if (buttonLevel == _buttonReleased) {
      _state = 2; // step to state 2

    } else if ((buttonLevel == _buttonPressed) && (now > _startTime + _pressTicks)) {
      _isLongPressed = true;  // Keep track of long press state
      if (_pressFunc) _pressFunc();
	  if (_longPressStartFunc) _longPressStartFunc();
	  if (_duringLongPressFunc) _duringLongPressFunc();
      _state = 6; // step to state 6
      
    } else {
      // wait. Stay in this state.
    } // if

  } else if (_state == 2) { // waiting for menu pin being pressed the second time or timeout.
    if (now > _startTime + _clickTicks) {
      // this was only a single short click
      if (_clickFunc) _clickFunc();
      _state = 0; // restart.

    } else if (buttonLevel == _buttonPressed) {
      _state = 3; // step to state 3
    } // if

  } else if (_state == 3) { // waiting for menu pin being released finally.
    if (buttonLevel == _buttonReleased) {
      // this was a 2 click sequence.
      if (_doubleClickFunc) _doubleClickFunc();
      _state = 0; // restart.
    } // if

  } else if (_state == 6) { // waiting for menu pin being release after long press.
    if (buttonLevel == _buttonReleased) {
	  _isLongPressed = false;  // Keep track of long press state
	  if(_longPressStopFunc) _longPressStopFunc();
      _state = 0; // restart.
    } else {
	  // button is being long pressed
	  _isLongPressed = true; // Keep track of long press state
	  if (_duringLongPressFunc) _duringLongPressFunc();
    } // if  

  } // if  
} // OneButton.tick()

// end.

**Comment by mathertel** [comment]
I just commited a version that checks for a bouncing signal.
The addition in in state 1: When the signal goes low too quickly nothing is done.
I may have to add similar checks on the other state transitions too.
