### ISSUE TITLE
how to get the RISING / FALLING?

### ISSUE THREAD

**Issue by moebiussurfing** [mathertel/OneButton#30]
is there any easy way to get the "start" of the pressed button?

when using a pulled up button, the library gets the click when it's released, but I would like to capture the RISING too...

**Comment by mathertel** [comment]
2 things to consider:
* you will have many ups and downs when using a digital input because of a bouncing signal. 
* You never know when it will be released at the start of a button pressure.
-> Be more precise on what you need and create a pull request please.
