### ISSUE TITLE
comparison between signed and unsigned integer expressions

### ISSUE THREAD

**Issue by JAY-M-ERICSSON** [mathertel/OneButton#35]
When compiling with a recent version of the compiler for Arduino (1.8.5), the compiler has a warning about the following

`
OneButton.cpp: In member function 'void OneButton::tick()':
.../OneButton.cpp:140:80: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if ((buttonLevel == _buttonReleased) && ((unsigned long)(now - _startTime) < _debounceTicks)) {
`

This is because  _debounceTicks is an int and should be an unsigned int (same goes for _clickTicks and _pressTicks)

So I suggest changing

` 
int _debounceTicks; // number of ticks for debounce times.

int _clickTicks; // number of ticks that have to pass by before a click is detected

int _pressTicks; // number of ticks that have to pass by before a long button press is detected
`

into

`
unsigned  int _debounceTicks; // number of ticks for debounce times.

unsigned  int _clickTicks; // number of ticks that have to pass by before a click is detected

unsigned  int _pressTicks; // number of ticks that have to pass by before a long button press is detected
`

**Comment by mathertel** [comment]
Thanks. included in version 1.3.0
