### ISSUE TITLE
Can't make it work on the Feather Huzzah

### ISSUE THREAD

**Issue by LimeBlast** [mathertel/OneButton#39]
I've tried using this library on my Feather Huzzah, but can't get it to compile.

I've added the following to my sketch, but am unable to build as I'm getting `error: 'D2' was not declared in this scope`.

```
OneButton button(D2);
```

From what I understand, the feather huzzah doesn't have the `A` and `D` pin definitions, and I'm unable to simply use an integer (2, in this case) as this is incompatible with the library.

Thanks.

**Comment by mathertel** [comment]
For an ESP8266 board you can use the GPIO numbers directly.
With `D2` normally GPIO4 is associated so just use
    OneButton button(4);
Hint: Some boards don't define the Dx constants. They originally came from the NodeMCU boards.
