### ISSUE TITLE
Debounce tick times

### ISSUE THREAD

**Issue by Rolbista** [mathertel/OneButton#55]
Hello

As far as I can see there is no way to set:
```
unsigned int _debounceTicks
unsigned int _clickTicks
unsigned int _pressTicks
```
whether via constructor or later during runtime, can you confirm this? If so, would you consider adding such a functionality or accepting a PR that adds it?

**Comment by JAY-M-ERICSSON** [comment]
I see [those functions in the API](https://github.com/mathertel/OneButton/blob/c8651328e3fd3513ffac95f5e012ebaf9a2b51e5/src/OneButton.h#L46-L53):

`  // set # millisec after safe click is assumed.
  void setDebounceTicks(int ticks);

  // set # millisec after single click is assumed.
  void setClickTicks(int ticks);

  // set # millisec after press is assumed.
  void setPressTicks(int ticks);
`

isn't that what you are looking for?

**Comment by Rolbista** [comment]
Yes, my bad. Tested and works fine, thank you.
