### ISSUE TITLE
Why are 'ticks' referenced as 1ms

### ISSUE THREAD

**Issue by ilium007** [mathertel/OneButton#57]
Throughout the code a 'tick' is referenced as 1ms. I am not sure of any uC where 1 'tick' corresponds to 1 ms

**Comment by mathertel** [comment]
many libraries have to be included in the loop() function execution. Some libraries call this tick() others expose a loop() function. - same implementation purpose behind this.
Maybe loop() is more common now but I avoid renaming to not break the compatibility.

See annotation in the new readme.md
