### ISSUE TITLE
Where did `attachLongPressStart` go?

### ISSUE THREAD

**Issue by cottsak** [mathertel/OneButton#6]
I'm interested in using `attachLongPressStart` as per https://github.com/mathertel/OneButton/blob/master/examples/TwoButtons/TwoButtons.ino however `OneButton.h` only defines:

```
  void attachClick(callbackFunction newFunction);
  void attachDoubleClick(callbackFunction newFunction);
  void attachPress(callbackFunction newFunction);
```

**Comment by cottsak** [comment]
The problem appears to be that the `OneButtonLibrary.zip` hosted on http://www.mathertel.de/Arduino/OneButtonLibrary.aspx is the wrong version. Please update the link to use the "Download ZIP" from Github: https://github.com/mathertel/OneButton/archive/master.zip

**Comment by mathertel** [comment]
fixed. I directly point to the download file on GitHub.
I will add the library to the Library Manager soon....
