### ISSUE TITLE
BUG: Invalid value of getPressedTicks on press stopped event was raised

### ISSUE THREAD

**Issue by ppetrov-dev** [mathertel/OneButton#62]
```
#include <Arduino.h>
#include "OneButton.h"
OneButton _button = OneButton(4, true, true);
void setup()
{
    Serial.begin(9600);
    Serial.println("Serial OK");

    _button.attachLongPressStop([]() { 
        Serial.println("Press Stop");
        Serial.print(_button.getPressedTicks());
        Serial.println(" ticks"); });
}
void loop()
{
    _button.tick();
}
```
output **everytime** when I release pressed button:
```
Press Stop
1001 ticks
```
**How to fix**: you have to remember ```_stopTime``` before raise events.
![image](https://user-images.githubusercontent.com/11585634/82751270-cbfe2900-9dbe-11ea-8632-8ea5602bb4f3.png). Threre are 3-4 such places in the code.

**Comment by mathertel** [comment]
great enhancement without breaking existing code or behaviour.
Will be in the next version.
