### ISSUE TITLE
Extending the OneButton class to support event based callbacks

### ISSUE THREAD

**Issue by rochdi80tn** [mathertel/OneButton#65]
In my project I have a set of buttons and the click handler is almost the same but does something different depending on the button (id)
I suggest adding internal functions to the class that will do nothing and will be overrided later in extended class.

**Comment by rochdi80tn** [comment]
Can someone give an example of the parametrized callbacks? It might solve my need..

**Comment by mathertel** [comment]
see comments in pull request #66
