### ISSUE TITLE
nano every

### ISSUE THREAD

**Issue by scottcowen** [mathertel/OneButton#74]
So i tried to compile your "Interrupt one button" example and it had this error

/home/scott/Arduino/libraries/OneButton-master/examples/InterruptOneButton/InterruptOneButton.ino: In function 'void setup()':
InterruptOneButton:40:3: error: 'PCICR' was not declared in this scope
   PCICR |= (1 << PCIE1);    // This enables Pin Change Interrupt 1 that covers the Analog input pins or Port C.
   ^~~~~
InterruptOneButton:40:18: error: 'PCIE1' was not declared in this scope
   PCICR |= (1 << PCIE1);    // This enables Pin Change Interrupt 1 that covers the Analog input pins or Port C.
                  ^~~~~
/home/scott/Arduino/libraries/OneButton-master/examples/InterruptOneButton/InterruptOneButton.ino:40:18: note: suggested alternative: 'PIN1'
   PCICR |= (1 << PCIE1);    // This enables Pin Change Interrupt 1 that covers the Analog input pins or Port C.
                  ^~~~~
                  PIN1
InterruptOneButton:41:3: error: 'PCMSK1' was not declared in this scope
   PCMSK1 |= (1 << PCINT9);  // This enables the interrupt for pin 1 of Port C: This is A1.
   ^~~~~~
InterruptOneButton:41:19: error: 'PCINT9' was not declared in this scope
   PCMSK1 |= (1 << PCINT9);  // This enables the interrupt for pin 1 of Port C: This is A1.
                   ^~~~~~
/home/scott/Arduino/libraries/OneButton-master/examples/InterruptOneButton/InterruptOneButton.ino:41:19: note: suggested alternative: 'PIN0'
   PCMSK1 |= (1 << PCINT9);  // This enables the interrupt for pin 1 of Port C: This is A1.
                   ^~~~~~
                   PIN0
exit status 1
'PCICR' was not declared in this scope

**Comment by mathertel** [comment]
The example uses direct registers of the processor in the original Arduino UNO so it cannot compile.

On Arduino EVERY you can also use the attachInterrupt to use interrupta.

```CPP
void checkTicks()
{
  // include all buttons here to be checked
  button.tick(); // just call tick() to check the state.
}

in setup():
  // setup interrupt routine
  // when not registering to the interrupt the sketch also works when the tick is called frequently.
  attachInterrupt(digitalPinToInterrupt(PIN_INPUT), checkTicks, CHANGE);
```

This will be part of the extended example in version 2.0.0 of the library.
