### ISSUE TITLE
Compile Warning

### ISSUE THREAD

**Issue by PowerBroker2** [mathertel/OneButton#78]
My sketch has been working great before this last update, but now I'm getting the following compile warning:

```
\Arduino\libraries\OneButton\src\OneButton.cpp: In member function 'void OneButton::tick(bool)':
\Arduino\libraries\OneButton\src\OneButton.cpp:223:10: warning: enumeration value 'UNKNOWN' not handled in switch [-Wswitch]
   switch (_state) {
          ^
Sketch uses 35712 bytes (1%) of program storage space. Maximum is 2031616 bytes.
Global variables use 49844 bytes (9%) of dynamic memory, leaving 474444 bytes for local variables. Maximum is 524288 bytes.
```

**Comment by mathertel** [comment]
What board /  compiler are you using ?

**Comment by PowerBroker2** [comment]
Sorry, Teensy 4.0 with the latest Arduino IDE version on Windows 10

**Comment by PowerBroker2** [comment]
Ok, strangely enough the warning has gone away without editing the lib files... interesting to say the least

**Comment by mathertel** [comment]
The warning appears only when compiling with the option to show ALL warnings.
I'll  take care.
