### ISSUE TITLE
removed attachPressStart

### ISSUE THREAD

**Issue by th0m4sek** [mathertel/OneButton#79]
pressStart is still mentioned in readme and changelog says that is same as attachLongPressStart but pressStart is activated without delay and longPressStart need to be active for 1 sec.
Consider adding it back.

**Comment by mathertel** [comment]
Thanks for pointing out to the difference between doku and implementation.
I just modified the doku.
This event had several problems e.g. was called multiple times. The library gave not much add on functionality here.
To detect that the button is pressed (no debounce etc.) just use digitalRead() on that pin in main loop.
