### ISSUE TITLE
attachMultiClick function not working

### ISSUE THREAD

**Issue by Deesi-Sunny-Willamson** [mathertel/OneButton#82]
Hi there, is it just me or is the attachMultiClick function not currently working
![attachMultiClick](https://user-images.githubusercontent.com/78896534/107607415-dfe60580-6c41-11eb-83c0-b73d96b73ff0.png)

**Comment by dotnetwise** [comment]
I am having the same issue - has this been implemented?

**Comment by mathertel** [comment]
Checked with the InterruptOneButton example that is works (as of now).
