### ISSUE TITLE
2 buttons together

### ISSUE THREAD

**Issue by arlimbad222** [mathertel/OneButton#83]
hello forks 

i am working on one small project & i want to run 2 button code together i attached my code here. it was like when button 1 print something with small delay and suddenly i press button 2 its not working. i just want print that button 2 thing when button 1 print something.

I dont have any coding experience so if it easy sorry for issue..

have a nice day my friends
[HELLO WORLD.TXT](https://github.com/mathertel/OneButton/files/5974002/HELLO.WORLD.TXT)

**Comment by mathertel** [comment]
The library doesn't support this but it can be built on top of the events from the individual buttons.

e.g. register to all LongPressStart and LongPressStop events of the buttons and find out that 2 of them actually started.
If you manage implementing an example, that would be welcome.
