### ISSUE TITLE
Parallel buttons press events

### ISSUE THREAD

**Issue by Rapid0s** [mathertel/OneButton#85]
Parallel button press events (single and long press) would be a nice feature for future updates.

To give an example lets say you have an array of 5 buttons and you want to trigger a special menu if two of the buttons are long pressed simultaneously.

**Comment by mathertel** [comment]
The library doesn't support this but it can be built on top of the events from the individual buttons.

e.g. register to all LongPressStart and LongPressStop events of the buttons and find out that 2 of them actually started.
If you manage implementing an example, that would be welcome.
