### ISSUE TITLE
Nesting button events inside callbacks?

### ISSUE THREAD

**Issue by MakerMatrix** [mathertel/OneButton#86]
I can't seem to get this to work and am starting to realize that depending on how this is implemented it may not be possible.

Are the callbacks running inside an interrupt?  If so, I guess you cannot detect another button press inside the callback?  And I also guess it would not be a good idea for the callbacks to run for a long time?  I may have to rethink how to do my project.  Is it better to have the button callbacks only toggle global boolean vars, and have those detected elsewhere?

What do you think?

I love the library by the way, VERY useful and easy to set up.  I think I'll use it a lot once I figure out some of these details.

Example sketch to aid in discussion:

```
#include "OneButton.h"

#define PIN_INPUT 13 // my board has the button soldered here

OneButton button(PIN_INPUT, false, false);  // It seems to be pulled high by default

void setup()
{
  Serial.begin(9600);
  Serial.println("One Button Example with polling.");

  // Setup the callbacks
  button.attachDoubleClick(doubleClick);
  button.attachLongPressStart(longClick);
  button.attachClick(shortClick);
} 

void loop()
{
  button.tick();
  delay(10);
}

// These two work as expected.
void doubleClick()
{
  Serial.println("Detected double-click.");
} 

void longClick()
{
  Serial.println("Detected long button press.");
}

// But nesting tick() inside a callback seems to break the library in a non-intuitive way.
void shortClick()
{
  Serial.println("Detected short button press.");

  while(1){
    button.tick();  // When we get here, the presses no longer reflect what is happening to the button.
    delay(10);
   }
}
```

**Comment by mathertel** [comment]
This doesn#t work as tick() cannot be called inside itself (shortClick will be called when button.tick() is called in your loop()  function. This will lead to a recursion because you never return from shortClick().

As a general rule: when a callback is done just change some global variables and then return.
In your loop function - check the variables and act as wanted.
