### ISSUE TITLE
Example InterruptOneButton.ino: confusion with pin numbers

### ISSUE THREAD

**Issue by FransCouwberghs** [mathertel/OneButton#87]
Minor problem although confusing with the example InterruptOneButton.ino. 
The comment 'Setup a test circuit' mentions to connect a pushbutton to A1 and GND and 'ButtonPin' as the identifier for it.
In the code pin 2 is used and 'PIN_INPUT' as identifier.
I connected my pushbutton as mentioned in the comment and the button did nothing.
After reading a bit of the code I corrected my mistake and it worked as intended.
Thought I should mention this.

Nice work on the library! It is really good!
I am currently working on a project with ATTiny84 where I use 6 buttons (4 trough OneButton).
Thanks to OneButton I am now converting an old scanner to a UV-Exposure box.

Thank You.

**Comment by mathertel** [comment]
Text updated.
