### ISSUE TITLE
getPressedTicks()

### ISSUE THREAD

**Issue by cranefist** [mathertel/OneButton#91]
getPressedTicks() Does not seem to exist?

**Comment by maxint-rd** [comment]
I missed it too! 
I've added this to OneButton.h in the class definition, just between the isLongPressed() method and the private: keyword
```
  int getPressedTicks() { return(millis()-_startTime); };   // MaxintRD 211230: Added missing method
```

**Comment by IhorNehrutsa** [comment]
Add getPressedMs() function in #124 
Use this function in the DuringLongPress and LongPressStop events to get the time since the button was pressed.

**Comment by mathertel** [comment]
fixed by https://github.com/mathertel/OneButton/pull/124
