### ISSUE TITLE
Analog or Digital?

### ISSUE THREAD

**Issue by fyrus7** [mathertel/OneButton#95]
Example sketch and Readme is confusing.

As i understand, if a code use "button 4" is digital pin. But in example sketch comment to use A1 which is an analog pin.

Which pin is the correct pin to use? Analog or digital?

**Comment by mathertel** [comment]
The library uses digital signals only.
Be sure to see the specs of your board.

E.g. the "Analog pins" on a Arduino UNO board support the Digital and Analog mode.
However they do not support attachInterrupt.
