### ISSUE TITLE
Request to bring back attachPressStart event

### ISSUE THREAD

**Issue by perkinsinnovation** [mathertel/OneButton#99]
I'd like to request that the attachPressStart event be added back to the next release.

I used this for various things through out my code, and I'll have to go back to an older version for now.

Thanks in advance for all of your hard work!

**Comment by DanBradshaw** [comment]
Hi, just wanted to add a +1 to this request. The click function seems to act on button release, not press. Thanks for all your work on this!

**Comment by mathertel** [comment]
On the first button press it is not yet possible to determine what kind of activity will happen.
See also #128
